### ISSUE TITLE
Flaggings contaminate the window in the model

### ISSUE THREAD

**Issue by wenyang-li** [EoRImaging/FHD#152]
I tested two runs for simulated visibilities: one has no flagging, and the other has flaggings from the real data. Both runs have 1 single observation,  exact the same data, no noise. The only difference is the flagging. I put both of them into firstpass to generate cubes then feed to eppsilon for ps. The following plot shows the power spectrum from both runs. The left plot has flaggings and the middle has no flagging, the right column shows left minus middle. 

![flagps](https://user-images.githubusercontent.com/18742340/54716025-2d779780-4b2b-11e9-9f2b-974e2486d858.png)

Clearly there are significant contaminations to the window. The flagging occupancy (other than times/frequencies being flagged all over the observation, which are marked as 0) is shown in the following plot. 

![flagging_occupancy](https://user-images.githubusercontent.com/18742340/54716273-c1496380-4b2b-11e9-9391-3e209cc4b80a.png)

I have also tested that if there is only whole times/frequencies flagging across the observation, the power spectrum is not contaminated. The contamination only happens when we have the sparse flaggings. 

In the real data, this level of contamination is still negligible. I tested MWA PhaseII zenith pointing sets, turns out with the sparse flagging filled/not filled, there is not any clear bias in the power spectrum.

**Comment by nicholebarry** [comment]
@mwilensky768 relevant

**Comment by nicholebarry** [comment]
@mwilensky768 Can you provide a brief summary of your understanding of this issue? I know you ran into something like this as well.

**Comment by mwilensky768** [comment]
Certain flagging patterns can indeed cause EoR window contamination. This is a generic problem with gridded power spectra (and probably delay spectra as well), cf. [this paper by Andre](https://arxiv.org/abs/1901.04752). Any given pattern produces a particular shape in the power spectrum. For instance, AOFlagger flags are somewhat random in frequency due to a small, but non-negligible amount of false positives, creating noisy contamination in the window. SSINS makes TV-shaped flags in the highband, causing lobed contamination in the window much like leaving DTV in the data would. This particular flavor of flagging contamination has an interesting shape in that it is banded in k_perp. My guess is that it is related to the redundant hex since this is phase II data. 

Since this is a generic power spectrum effect that, as far as I understand, happens independently of FHD, this is not an FHD-specific issue and so it should be closed. It will be further documented in the literature in addition to what exists in the link above.
