### ISSUE TITLE
Imaging artifact in Stokes Q and U when long baselines are excluded

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#154]
Stokes Q and U images have a discontinuity that is only visible when long baselines are excluded from imaging. 

Here is an example. For this run, baseline_threshold=-50, meaning that only baselines shorter than 50 wavelengths were used:
Stokes Q Dirty:
![1131713632_uniform_Dirty_Q](https://user-images.githubusercontent.com/12840057/54898620-38fbf300-4e8a-11e9-9e02-0727effb9db5.png)
Stokes U Dirty:
![1131713632_uniform_Dirty_U](https://user-images.githubusercontent.com/12840057/54898628-3f8a6a80-4e8a-11e9-8192-7676e77a7a74.png)

For reference, here is the same observation with identical calibration, now imaging with all baselines. Here you can't see the artifact:
Stokes Q Dirty:
![1131713632_uniform_Dirty_Q (1)](https://user-images.githubusercontent.com/12840057/54898685-7f515200-4e8a-11e9-90db-5e41fd2a8fb7.png)
Stokes U Dirty:
![1131713632_uniform_Dirty_U (1)](https://user-images.githubusercontent.com/12840057/54898690-82e4d900-4e8a-11e9-8d24-bad50ffef560.png)

This artifact often appears at the center of the observation but not always. In this observation it's in the top part:
Stokes Q Dirty:
![1130773144_uniform_Dirty_Q](https://user-images.githubusercontent.com/12840057/54898927-4bc2f780-4e8b-11e9-95f4-c1ecaef2c364.png)
Stokes U Dirty:
![1130773144_uniform_Dirty_U](https://user-images.githubusercontent.com/12840057/54898940-59787d00-4e8b-11e9-9ba0-e6a2720dad84.png)

**Comment by isullivan** [comment]
It looks like the discontinuity is always located at zenith. Is that correct? I suspect it is present in the dirty images as well, but it's hard to see since the color scale is ~10x larger. If you save the dirty Stokes images as fits files and zoom in at zenith and maybe smooth them a little, can you see this feature?

**Comment by rlbyrne** [comment]
@isullivan These are the dirty images. Do you mean the all-baselines images?

**Comment by rlbyrne** [comment]
Here I've plotted the residual fits images around the imaging artifact with all baselines and with the baseline cut. I really can't say if the imaging artifact just isn't there when we use all baselines or if it's just masked by the small-scale structure.
![StokesQ_residual_all_baselines](https://user-images.githubusercontent.com/12840057/54955812-9a17db00-4f0b-11e9-97bb-6507dad94da9.png)
![StokesQ_residual_baseline_cut](https://user-images.githubusercontent.com/12840057/54955820-9d12cb80-4f0b-11e9-8ee7-8178ba507a9a.png)

**Comment by bhazelton** [comment]
We just discussed this. It appears that the Jones matrix is being interpolated to RA/Dec locations but the basis vectors are not being rotated to align with RA/Dec. 

We need to calculate the paralactic angle per pixel, including refraction, nutation, etc.., and use that angle to rotate the Jones matrix when constructing the antenna beam model. This needs to be an option, so that it is only used when constructing a Jones matrix, and not for the beam model used to grid visibilities (so there should be no effect on the eppsilon PS or on unpolarized sources).
