### ISSUE TITLE
psf_resolution

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#192]
The default is set in multiple locations in the code. In the antenna struct, it's set to 16. In the psf struct, it's set to 1. We should find out which is the true default and delete the other

**Comment by mwilensky768** [comment]
I think this comes down to choosing the more sensible default of the two. If it makes more sense to overresolve by a factor of 16 more often than not overresolving at all, then I say we pick 16. Otherwise, we pick 1.

Based on the fact that it gets set in two places, I think it's possible that one could arrive at either default in any order (one does not necessarily come before the other). Maybe we set them to be identical, instead of deleting one of them?

**Comment by isullivan** [comment]
16 is the real default. The one in defining the psf struct was just a placeholder.

**Comment by mwilensky768** [comment]
I believe this was closed by #219
