### ISSUE TITLE
Add support for Antenna1 and Antenna2 optional group parameters in uvfits

### ISSUE THREAD

**Issue by bhazelton** [EoRImaging/FHD#47]
These arrays list the antennas going into each visibility, getting around the unique baseline definition that can be unclear with more than 255 antennas.

**Comment by isullivan** [comment]
Added to master, git version v3.5-175-geb4cd50
Tested for backwards compatibility on older data, and it doesn't seem to break anything. I don't have any new data with antenna numbers in the uvfits parameters, so I have not tested that it works.

**Comment by mkolopanis** [comment]
I have tested running FHD with HERA 331 simulations and errors since no `BASELINE` parameter exists in the uvfits header (as expected).  Any updates on getting compatibility with large antenna numbers (>255)?

if you need some simulated data for a large array there is hera 331 simulation on enterprise:
 `enterprise : /data4/HERA_Simulations/simulations/project_WEDGE_POWER/HERA_331/simdata `
