### ISSUE TITLE
Getvar_savefile couldn't find antenna.sav

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#57]
I just noticed that the log output of an FHD firstpass run consistently has the error below (shown in the output snippet). FHD runs finish just fine even though this occurs, and I really don't know how long this error has been there. It's probably just a naming issue.

Low priority, obviously.

```
Gridding visibilities
Gridding time:      402.014      392.936
Gridded visibilities not deconvolved
Exporting (quickview): 1061315808
Image output timing (quickview):        59.420220
getvar_savefile: file /nfs/mwa-09/r1/djc/EoR2013/Aug23/fhd_nb_gleam_firstpass/beams/1061315808_antenna.sav not found
Gridding timing: 717.16910
Gridding timing: 709.02437
HEALPix cube export timing:        2538.2609       1992.7253      0.00000
Full pipeline time (minutes): 204

Finished
```

**Comment by isullivan** [comment]
That is either a feature or a bug, depending on how you look at it, but it is at least intentional. The antenna structure is quite large but fast to create, so it is deliberately not saved to save disk space. We will probably want to change that once we include known dead dipoles to construct a different beam for each tile.

**Comment by nicholebarry** [comment]
As long as it is intentional!
